---
- name: Install packages for Kubernetes cluster
  hosts: "{{ host_group }}"
  become: true
  tasks:
    - name: Ensure dependencies are installed.
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg
        state: present

    - name: Add k8s.conf
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load kernel modules
      command: modprobe {{ item }}
      with_items:
        - overlay
        - br_netfilter
      become: true

    - name: Sysctl params required by setup, params persist across reboots
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Apply sysctl settings
      command: sysctl --system
      become: true

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Install Docker key
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Change permissions on Docker key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: 0755

    - name: Get system architectire
      command: dpkg --print-architecture
      register: _result_arch

    - name: Add Docker repository to sources.list
      copy:
        content: |
          deb [arch={{ _result_arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        dest: /etc/apt/sources.list.d/docker.list

    - name: Run apt-get update
      command: apt-get update
      become: true

    - name: Install containerd.io
      apt:
        name: containerd.io
        state: present

    - name: Edit containerd config
      copy:
        content: |
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
              SystemdCgroup = true
        dest: /etc/containerd/config.toml
        group: root
        owner: root
        mode: 0755

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted

    - name: Add Kubernetes apt key.
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes repository.
      apt_repository:
        repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
        state: present
        update_cache: true

    - name: Install Kubernetes packages.
      apt:
        name:
          - kubelet
          - kubectl
          - kubeadm
        state: present

    - name: Create kubeadm config
      copy:
        content: |
          apiVersion: kubeadm.k8s.io/v1beta3
          kind: ClusterConfiguration
          kubernetesVersion: stable
          controlPlaneEndpoint: "10.10.104.16:6443"
          ---
          kind: KubeletConfiguration
          apiVersion: kubelet.config.k8s.io/v1beta1
          cgroupDriver: systemd
        dest: /var/kubeadm-config.yaml
        group: root
        owner: root
        mode: 0755
      when: inventory_hostname in groups["kubernetes_master"]
